generic-webhook-trigger.yaml: Fix the webhook
Trying to fix the deployment caused by:
io.jenkins.plugins.casc.UnknownAttributesException: unclassified:
Invalid configuration elements for type: class
jenkins.model.GlobalConfigurationCategory$Unclassified : genericWebhookWhitelist.